# Generated by Django 2.2.7 on 2019-11-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
