# Generated by Django 2.2.7 on 2019-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191120_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sliders')),
            ],
            options={
                'verbose_name': 'HomePage Slider',
                'verbose_name_plural': 'HomePage Sliders',
                'db_table': 'home_sliders',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'WOMEN'), (2, 'MEN')], null=True),
        ),
    ]
