# Generated by Django 2.2.7 on 2019-11-27 12:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191127_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[370, 370], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1_b',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[570, 570], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[370, 370], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2_b',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[570, 570], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[370, 370], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3_b',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[570, 570], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[370, 370], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4_b',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[570, 570], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[370, 370], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5_b',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[570, 570], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[370, 370], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6_b',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=90, size=[570, 570], upload_to='products'),
        ),
    ]
