# Generated by Django 2.2.7 on 2019-11-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191123_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.IntegerField(blank=True, choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Diamond')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'WOMEN'), (2, 'MEN'), (3, 'UNISEX')], default=3, null=True),
        ),
    ]
