# Generated by Django 2.2.7 on 2019-11-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191127_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
    ]
