# Generated by Django 2.2.7 on 2019-11-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191123_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='testimonials')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials',
            },
        ),
        migrations.RenameModel(
            old_name='HomeSlider',
            new_name='Slide',
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelTable(
            name='slide',
            table='slides',
        ),
    ]
