# Generated by Django 2.2.7 on 2019-12-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='description_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='text1_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='text1_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='text2_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='text2_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
