# Generated by Django 2.2.7 on 2019-11-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191124_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text2',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials'),
        ),
    ]
